#!/usr/bin/env bash
#-------------------------------------------------------------------------------
#  Copyright 2021 Pax, Schweizerische Lebensversicherungs-Gesellschaft AG
#
#  Licensed under the Pax License, Version 1.0 (the "License");
#-------------------------------------------------------------------------------
#
# @Description
# copy markdown readme files (generated by stencil with manual additons) to
# storybook stories as mdx files
#
#-------------------------------------------------------------------------------

echo "copying markdown to stories"
cd src/components
for readmefiles in **/*.md; do
  name=${readmefiles%/*}
  cp ${readmefiles} ../../../stories/components/${name}.mdx
done
cd ../..
